[package]
name = "kernel-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = []
default = []

[dependencies]
gen_font = { path = "../gen_font" }
common = { path = "../common" }
