name: Rust lint & test

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v3
      - name: Set Toolchain
        # https://github.com/dtolnay/rust-toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: setup
        run: rustup component add rust-src --toolchain nightly-2023-07-11-x86_64-unknown-linux-gnu
      - name: Run check
        run: make check
      - name: Run rustfmt
        run: make fmt_ci
      - name: Run clippy
        run: make clippy_ci

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v3
      - name: Set Toolchain
        # https://github.com/dtolnay/rust-toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Run test
        run: make test_all
